### ISSUE TITLE
在Win系统下部署的bot无法进行stat.ink同步

### ISSUE THREAD

**Issue by Hana-Akira** [paul-sama/splatoon3-bot#28]
> 02-20`` 00:13:51 [   INFO] nonebot.matcher:830 | Matcher(type='message', module=splatoon3_bot.plugins.splatoon3_nso.cmd_set, lineno=329) running complete
sed：-e 表达式 #1，字符 1：未知的命令：“'”
sed：-e 表达式 #1，字符 1：未知的命令：“'”
sed：-e 表达式 #1，字符 1：未知的命令：“'”
Exception in thread Thread-11 (sync_stat_ink_func):
Traceback (most recent call last):
  File "D:\Python3.10\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Python3.10\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Hana-NAS\Desktop\Splatoon-TG\splatoon3-bot\splatoon3_bot\plugins\splatoon3_nso\sp3job.py", line 148, in sync_stat_ink_func
    msg = get_post_stat_msg(u.id)
  File "C:\Users\Hana-NAS\Desktop\Splatoon-TG\splatoon3-bot\splatoon3_bot\plugins\splatoon3_nso\sp3job.py", line 260, in get_post_stat_msg
    res = exported_to_stat_ink(u.id, u.session_token, u.api_key, u.acc_loc)
  File "C:\Users\Hana-NAS\Desktop\Splatoon-TG\splatoon3-bot\splatoon3_bot\plugins\splatoon3_nso\sp3job.py", line 232, in exported_to_stat_ink
    rtn = subprocess.run(cmd.split(' '), stdout=subprocess.PIPE).stdout.decode('utf-8')
  File "D:\Python3.10\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Python3.10\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python3.10\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] 拒绝访问。

1.貌似是sed的命令格式有问题？能否提供解决方案。
2.目前只有tg有代理配置，能否添加访问NSO和上传对战记录到stat.ink的代理配置。
先提前感谢解答

**Comment by paul-sama** [comment]
1.可以在win下单独安装https://sourceforge.net/projects/gnuwin32/files/sed/

2.试试最新的项目
https://github.com/Cypas/splatoon3-nso
